### ISSUE TITLE
Implement button that will allow to load NeXus directly from the manual reduction ui

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/PyRS#126]
This button will, in fact, create a project file and automatically load it.

**Comment by peterfpeterson** [comment]
For the multi-threading, this should use mantidworkbench’s `mantidqt.utils.asynchronous.AsyncTask` ([example](https://github.com/neutrons/addie/blob/master/addie/processing/mantid/launch_reduction.py#L28)) to do the multi-threading.

The gui should do the equivalent work of `scripts/reduce_HB2B.py` without “viewraw” or “subruns” options being supplied

**Comment by peterfpeterson** [comment]
This is done
