### ISSUE TITLE
Testing Data Summary

### ISSUE THREAD

**Issue by fanchercm** [neutrons/PyRS#137]
**Summary**

IPTS-22731

Run 931 as a Vanadium Flood to normalize the data
Run 934: for peak fit testing.
Run 938: the instrument configuration is changed.  It has better data for peak fitting.

**11.11**
Run 1017: One with nice peak (better background and etc)
Run 1022: Verify geometry

**Comment by fanchercm** [comment]
Use run 934 for peak fit testing.

**Comment by fanchercm** [comment]
We changed the instrument configuration. Run 938 has better data for peak fitting.

**Comment by wdzhou** [comment]
Run 931 as a Vanadium Flood to normalize the data

**Comment by wdzhou** [comment]
@fanchercm : Some sample logs in nexus files are lists (Strain Direction) in run 917

**Comment by peterfpeterson** [comment]
This is already
