### ISSUE TITLE
Fitting UI changes plan

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/PyRS#176]

**Comment by JeanBilheux** [comment]
Here are the changes discussed during the 11/27/19 meeting

**Attendees:** 
Chris, Jeff, Steve, Jean

- browsing for NeXus project file should be removed and replace by **IPTS** and **Run NUmber** widgets. By default the program will go into the _IPTS/shared/pyrs_reduction/_ folder in order to retrieve the project file. If this one is missing, program will go to the /IPTS/shared/autoreduce folder instead. 
- plot on the rigth will have less x and y-axis options. The list of x-axis and y-axis will be provided by Jeff.
- bottom right plot will be a contour plot (not a 3D plot). For this we will use pyqtgraph
- top and bottom right plots should have each their set of x and y-axis dropdown list.
- bottom right plot will have the option to select a range or discrete list of sub-runs using Mantid convention (ex: 1,4:10 -> 1,4,5,6,7,8,9,10)

Output
- allow users to export plots (png, if possible with at least 300dpi)
- save workspaces

**Comment by JeanBilheux** [comment]
- [ ] Add an item to the x/y-axis dropdown list called **strength**. When the user selects this option, a text box with a label *d0* should show up to let the user define this value in order to calculate the strength *((d - d0)/d0)*. d0 is in microstrength unit. 
- [ ] new widget that let the user select which **peak tag** they want to see for either the 1D and 2D plots  - check with IS about this to make sure this option is necessary for both
- [ ] Add a 3rd dimension to the 2D plot.

**Comment by fanchercm** [comment]
I would suggest changing point 1) to "strain". The units for d0 are the same as d (Angstrom). The UI should display (d - d0)/d0) * 1E6, with units of microstrain.

**Comment by JeanBilheux** [comment]
File HB2B_1060.h5 is a good file to test UI for IPTS-22731
/HFIR/HB2B/IPTS-22731/shared/ProjectFiles/HB2B_1060.h5

**Comment by peterfpeterson** [comment]
#756 was created to capture an error with this

**Comment by peterfpeterson** [comment]
This is done other than the bug described in #756, and the 3rd dimension which is actually a feature for the strain/stress GUI
