### ISSUE TITLE
Add gui element to export csv summary

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#202]
This is adding the results of #97 to the gui. It should be a "browse" button to select the output file then running the code similar the integration test.

**Comment by peterfpeterson** [comment]
@JeanBilheux I believe you are correct that this goes in the fitting UI

**Comment by JeanBilheux** [comment]
- [ ] Move **Save As** to the file menu
- [ ] remove **Save** and do this automated
- [ ] **Export CSV** button will replace the current **Save As** and **Save**
