### ISSUE TITLE
PV headers and Data are mismatched in CSV output

### ISSUE THREAD

**Issue by jefrbunn** [neutrons/PyRS#261]
A check would be in run 1305 where:

`sx` moves between -10 and 10 in 0.5mm steps

and `ISD `should be the same as `HB2B:Mot:ISD` which is moving from 65 to 240 every 21 subruns a 5 mm step. `HB2B:Mot:ISD `is correct but the `ISD `and `ISD `setpoint are not

**Comment by peterfpeterson** [comment]
Things that should be done to fix this:
* peak names/tags should replace `,` with `_`
* [`SampleLogs. constant_logs `](https://github.com/neutrons/PyRS/blob/master/pyrs/dataobjects/sample_logs.py#L81) should also check that things that aren't plottable (read: non-numeric)

**Comment by peterfpeterson** [comment]
This is no longer an issue. Verified using `HB2B_1060.csv`
