### ISSUE TITLE
Remove logs after reading nexus file

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#272]
[`RemoveLogs`](https://docs.mantidproject.org/nightly/algorithms/RemoveLogs-v1.html) can be used with a whitelist to remove all logs that are not interesting. To speed up the initial event filtering (and calculating effective log values), remove logs that aren't in a whitelist. The event filtering code should have a list of logs that are always kept, and an additional property (default value is empty list) of logs to keep.

The new code can happen right after [loading the metadata from the nexus file](https://github.com/neutrons/PyRS/blob/master/pyrs/core/nexus_conversion.py#L254) and [load_split_sub_runs](https://github.com/neutrons/PyRS/blob/master/pyrs/split_sub_runs/load_split_sub_runs.py#L82).

**Comment by peterfpeterson** [comment]
Without information from the instrument scientists, you can still keep the list [suggested here](https://github.com/neutrons/PyRS/blob/master/pyrs/core/summary_generator.py#L22-L23).

**Comment by jefrbunn** [comment]
`experiment_identifier
run_number
run_title
file_notes
start_time
end_time
SampleId
SampleName
SampleDescription
StrainDirection
hklPhase
Filename
sub-run
sub-run duration
mrot
mtilt
mb220
mb511
ISD
ISR:X:Gap
ISR:Y:Gap
DOX
DOY
DOR
omega
2theta
phi
chi
sx
sy
sz
vx
vy
vz`

[HB2B log Whitelist.txt](https://github.com/neutrons/PyRS/files/4130642/HB2B.log.Whitelist.txt)

**Comment by jefrbunn** [comment]
Quick Edit to the white-list, we should also include the wavelength (from calibrated .JSON file) on the list

see edited comment above
