### ISSUE TITLE
Improve fitting

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#293]
Current peak fitting does not give terribly good results in the general case. Certain things can be done to make it better:
1. Improve initial guess of peak location through either starting with the position of the maximum, or by calculating the first moment of the function
2. Modify mantid's `FitPeaks` to better set initial guesses for pseudo-Voigt. The issue is that it sets things using effective parameters and pseudo-Voigt needs the mixing parameter set first.

**Comment by JeanBilheux** [comment]
Values and error return by get_effective_params() are identical, except for the Height. 

*Values*
![Screen Shot 2020-01-22 at 11 04 24 AM](https://user-images.githubusercontent.com/1138324/72910762-0075b180-3d07-11ea-9771-eeb832a7ef40.png)

*Errors*
![Screen Shot 2020-01-22 at 11 04 30 AM](https://user-images.githubusercontent.com/1138324/72910782-07042900-3d07-11ea-9d77-0fe0c50f2a54.png)

**Comment by peterfpeterson** [comment]
The issue Jean is pointing out is specifically for the pseudo-Voigt. Gaussian is fine.

**Comment by peterfpeterson** [comment]
A separate issue has been created for the pseudo-Voigt uncertainties #303

**Comment by peterfpeterson** [comment]
[mantid PR27809](https://github.com/mantidproject/mantid/pull/27809) fixes the last bits of this issue.
