### ISSUE TITLE
Fix effective parameter errors for pseudo-Voigt

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#303]
The errors reported by `PeakCollection.get_effective_params()` match the values when the peak shape is pseudo-Voigt. The errors for Gaussian are correct.

Add a unit test for pseudo-Voight to `tests/unit/test_peak_collection.py`. The existing test should be renamed to reflect that it is only for Gausssian.

**Comment by Fahima-Islam** [comment]
@peterfpeterson  do you mean ```The errors reported by PeakCollection.get_effective_params() **_does not_**  match the values when the peak shape is pseudo-Voigt. The errors for Gaussian are correct.``` ?

**Comment by peterfpeterson** [comment]
This was fixed in #320
