### ISSUE TITLE
Manual reduction UI tasks before Feb 1

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#315]
As following:
1. Re-org codes #314 
1. Masking #319
1. Plot detector view #256 
1. Plot powder pattern (working)
1. Better management on running split with thread pool
1. Reduction status table, columns: [sub run, split, powder]
1. 'sub run combo box' could update the plots with new  selection
1. Split and reduction can update table in realtime

**Comment by peterfpeterson** [comment]
No longer valid
