### ISSUE TITLE
January 30, 2020 push

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#316]
What was agreed upon as a short term deliverable is:
* [x] Reduction of nexus file to a hidra project file containing powder patterns for each subrun. Selecting a mask and instrument calibration through the pyrsplot manual reduction gui is part of this.
* [x] Load that project file into the pyrsplot fitting gui, select a region of interest, and fit pseudo-Voigt peak to the data there
* [x] Fitting GUI provides option to plot the fitting parameters vs subrun (top upper right plot)
* [x] Pseudo-Voigt peak fitting gives reasonable results
* [x] Data can be exported to csv

**Comment by JeanBilheux** [comment]
2 out of 4 done . :-)
But I think you need to add the option to plot the fitting parameters vs sub runs for example (my top right plot).. .which is what i'm working on today.

**Comment by peterfpeterson** [comment]
Everything requested in this issue works with maintenance work left to be done.
