### ISSUE TITLE
PeakCollection work with wavelength

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#318]
There should be an additional attribute on `PeakCollection` for wavelength. This will be used for calculating the d-spacing of a peak. As a result the accessor methods will be:
* `get_native_parameters()` to get the parameters of the peak function
* `get_effective_parameters()` to get the center, height, fwhm, mixing, A0, A1 and intensity
* `get_dspacing_center()` to get the effective center and uncertainty converted to d-spacing

Second part is to modify `pyrs.core.summary_generator.SummaryGenerator` with the `<peak_tag>_dspacing_center` being the first column in the peak section and `<peak_tag>_dspacing_center_error` being the first column in the peak uncertainty section.

**Comment by Fahima-Islam** [comment]
@peterfpeterson where would the `wavelength` be initialized? Is it at the time of object instantiation?

**Comment by wdzhou** [comment]
@Fahima-Islam @peterfpeterson I think it a good idea.  Usually the instrument team won't change wave length during a **run**.

**Comment by peterfpeterson** [comment]
This only requires that they have decided the wavelength before fitting begins. It means it isn't really an issue.

**Comment by peterfpeterson** [comment]
Thinking more/talking with people. Please set the default wavelength to `np.nan` for the case of it not being set. That way all of the d-values, strain, and stress calculations will be full of NaNs.
