### ISSUE TITLE
Create a file utils class that will handle various file utilities

### ISSUE THREAD

**Issue by JeanBilheux** [neutrons/PyRS#336]
We need a class that can handle various file utilities for the entire project such as
- find a ipts from a run number `get_ipts(runnumber)`
- find a nexus from a run number `get_nexus(runnumber)`
- find the default output folder for a runnumber `get_default_output_dir(runnumber)`
- ~~find the default output folder for an ipts~~
- find the ipts directory from a run `get_ipts_dir(runnumber)`
- `get_input_project_file(runnumber)` returns manual, then autoreduction, then throw an exception

![IMG_4500](https://user-images.githubusercontent.com/1138324/73458108-bf9f1d80-4342-11ea-8583-b57df0818169.JPG)

**Comment by peterfpeterson** [comment]
This should go in `pyrs/utilities/file_util.py`
