### ISSUE TITLE
Strain calculation

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#338]
The strain is `(d_fitted - d_reference)/d_reference`. This will be done by adding functions to`PeakCollection`:
* `set_d_reference(self, value)` which will take either a single float or a ndarray of floats (same number as subruns) and assign it to a member variable
* `get_d_reference(self)` which will return a ndarray of floats (same number as subruns)
* `get_strain(self)` which will do the calculation and return both value and error as parallel ndarrays

The default value of the d_reference should be nan.

**Comment by wdzhou** [comment]
Method get_strain will calculate strain every time it is called?

**Comment by wdzhou** [comment]
Also I suggest separate tasks for unit test and integration test.

**Comment by Fahima-Islam** [comment]
> Method get_strain will calculate strain every time it is called?

Yes.
