### ISSUE TITLE
Add uncertainties and subruns to powder patterns in project files

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#387]
As pointed out in #310, the `reduced diffraction data` does not have uncertainties. This would also be a good time to add the extra attributes so it is [plottable NeXus data](https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata). This means that the `reduced diffraction data` group should have additional attributes:
* `NX_class` with value `NXdata`
* `signal` with value `main` 
* `axes` with value `["2theta", "subrun"]`

There should be additional fields
* `subrun`
* `2theta` gets a `units` attribute
* `main_error`

**Comment by fanchercm** [comment]
data uncertainty was added in #403
