### ISSUE TITLE
Explore errors on fitting results

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#397]
Reported by Andrew:

Chris and I have compared notes. Compared to LMfit, our fitting is giving error estimates that are too large by a factor of about 50X (for peak center). The mixing error is huge too. Something is clearly very very WRONG with this calculation.  This is for data sets with very well resolved peaks, e.g. IPTS-22152, run number 1360.

**Comment by EAPayzant3** [comment]
Fitting this data with a gaussian yields good results with bogus errors - they are clearly way too big. Something is seriously wrong with Mantid's error analysis/propagation for peak fitting.

**Comment by fanchercm** [comment]
difference in errors are found to occur because prorogation of error was not used. see commit #403
