### ISSUE TITLE
Improve file save/load user experience for peak fitting module

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#44]
According to meeting on Nov. 1st:

1. Need more buttons for saving fitting result
2. New use case: if user loads a HDF5 and entry ‘peak fit’ is found, user will be prompted whether he wants to fit the peaks again
3. Peak fitting result shall be saved to HDF5 (input file) automatically (with flag)

**Comment by peterfpeterson** [comment]
This is already done
