### ISSUE TITLE
Add test data for multiple project files combining into a single StrainField

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#527]
Suggested by Jeff:

> There are actually 4 files we could combine into one dateset I believe - however some points will have no peak data in actuality as we use it to check offsets do to optics.
> 
> Combine: 1331,1332,1327,1328

**Comment by jefrbunn** [comment]
I would combine Run 1327 and Run 1328 (single direction over 2 scans)

**Comment by jefrbunn** [comment]
There are actually 4 files we could combine into one dateset I believe - however some points will have no peak data in actuality as we use it to check offsets do to optics.

Combine: 1331,1332,1327,1328

**Comment by jmborr** [comment]
@jefrbunn Do you have any project file containing Peak information for any of these four runs?
