### ISSUE TITLE
StressField holds onto the 3 StrainFields

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#535]
Since the in-plane stress assumption needs to have a StrainField to fulfill the assumption, it may be better to store the actual 3 StrainFields.

**Comment by williamfgc** [comment]
Addressed by #545

**Comment by rosswhitfield** [comment]
This requires for in-plane stress e33 to be calculated according to equation 7 in https://github.com/neutrons/PyRS/blob/master/docs/stress_strain.pdf

**Comment by peterfpeterson** [comment]
I think the 3rd stress might actually be initialized correctly already. It is definitely [calculated already](https://github.com/neutrons/PyRS/blob/master/pyrs/dataobjects/fields.py#L940-L948).

**Comment by rosswhitfield** [comment]
We need the 3rd strain not stress

**Comment by rosswhitfield** [comment]
Currently it's just being set to zero https://github.com/neutrons/PyRS/blob/master/pyrs/dataobjects/fields.py#L936

**Comment by rosswhitfield** [comment]
Closing this for #587
