### ISSUE TITLE
Recalculate strains and stresses after d_0 modification

### ISSUE THREAD

**Issue by jmborr** [neutrons/PyRS#612]
Requires #525 

### Algorithm to recalculate the strain and stress after a change in the reference lattice spacing

**Inputs:**
- `stress`, a `StressField` object.
- `d_0`, a `ScalarFieldSample` object defined over the sampling points of `stress`

**Outputs:**
- `stress_new`, a `StressField` object (contains new strains and stresses for every direction)

**Actions:**
- Iterate over each direction, pulling the strain (`strain11`, `strain22`, `strain33`) and performing the following actions:
  + Iterate over the list of `PeakCollection` objects along the current directoin, performing the followig actions:
     * Update `PeakCollection._d_0` with input `d_0`. Updating algorithm described below
     * Calculate a new `StrainField` object from the updated `PeakCollection`
  + Combine the strains along the current direction
- Obtain a new `StressField` object by stacking the new strains along the scanned directions

### Algorithm to update a `PeakCollection` object after a change in the reference lattice spacing

**Inputs:**
- `pc`, one `PeakCollection` object
- `d_0`, a `ScalarFieldSample` object. The new reference lattice spacing.

**Outputs:**
- `None`. Object `pc` is updated in-place

**Caveat**:
The set of sample points over which `d_0` is defined is different than the set of sample points of `pc`. Usually it will be much larger than because `d_0` is defined over the set of sample points resulting of (possibly) combining  several peak collections along the same direction, and then stacking three (or two) strains related to different directions. Alternatively, the user may choose to modify `d_0` only over a small region of interest, in which case the associated set of sampling points will be much smaller than the set of sample points of `pc`.

**Proposed solution**:
Let `pl` be the `PointList` object representing the set of sample points  of PeakCollection `pc`, and let `PL` the `PointList` object representing the set of sample points of `d_0`. A _cross-reference index table_ will establish a relationship between one point in `pl` to one point in `PL`.  
```
table[i] = (J, j)
```
where `i` is an index identifying one of the points of `PL`; `J` is an index identifying one of the PeakCollections used to create `PL`; `j` is an index identifying one of the points of PeakCollecion `j`.

**Comment by jmborr** [comment]
Work done and comments by Pete, to be reviewed and addressed:

#### StrainField.field is super simple for missing points  
They'll be at the end of the PointList and not get a value assigned to them

#### I have fuse_with sorted out (working on stack now).  
Does the code look more sensible now?  
https://github.com/neutrons/PyRS/compare/525_peak_collection_with_position

#### `a.intersection(a)` should give `a`. It doesn't
```
        x = [0.0, 0.5, 0.0, 0.5, 0.0, 0.5, 0.0, 0.5]  # x
        y = [1.0, 1.0, 1.5, 1.5, 1.0, 1.0, 1.5, 1.5]  # y
        z = [2.0, 2.0, 2.0, 2.0, 2.5, 2.5, 2.5, 2.5]  # z
        point_list1 = PointList([x, y, z])
        # changes a single x-value in the last 4 points
        x = [0.0, 0.5, 0.0, 0.5, 1.0, 1.5, 1.0, 1.0]  # x
        y = [1.0, 1.0, 1.5, 1.5, 1.0, 1.0, 1.5, 1.5]  # y
        z = [2.0, 2.0, 2.0, 2.0, 2.5, 2.5, 2.5, 2.5]  # z
        point_list2 = PointList([x, y, z])
```
Try intersect with those

#### Look at the "test_small_stack" for what I have (mostly) working
- It appears to have exposed a bug in PointList.fuse_with
- There is something wrong with setting the values on the new object

**Comment by peterfpeterson** [comment]
I believe the bits of this for `StrainField` were already dealt with in #656

**Comment by peterfpeterson** [comment]
Either there needs to be a callback from `StrainField` to `StressField` or the values need to be calculated on the fly

**Comment by peterfpeterson** [comment]
The rest of this will be done in #683
