### ISSUE TITLE
Load a hidra project file using the run number entry in the Peak Fitting UI

### ISSUE THREAD

**Issue by fanchercm** [neutrons/PyRS#624]
The peak fitting UI was initially designed with the potential to load data using a file dialog (Browse Exp. Data File) or by entering a run number in the input text box located to the left of the "Browse Exp. Data File" button. 

Question: What is the best mechanism to handle a run number having a datafile in both the autoreduce and manualreduce folders?

**Comment by rosswhitfield** [comment]
Reminder to self, use https://github.com/neutrons/PyRS/blob/891747308823794076441dae2fba51220b6bc581/pyrs/utilities/file_util.py#L178
