### ISSUE TITLE
Reduction Manager does not exclude runs from project file

### ISSUE THREAD

**Issue by fanchercm** [neutrons/PyRS#626]
The PyRS powder reduction process requires a sub-run list input, with an empty list or None dictating that all subruns are reduced:
https://github.com/neutrons/PyRS/blob/fa6600fdcc5c68a2d499f1b566ac119497ad33fc/pyrs/core/powder_pattern.py#L85

This input gives the impression that a user or beamline staff member could specify a specific set of subruns they want to reduce into the projectfile. 
https://github.com/neutrons/PyRS/blob/fa6600fdcc5c68a2d499f1b566ac119497ad33fc/scripts/reduce_manual_HB2B.py#L80
Specify the sub-run list only changes what data are reduced into 1D data. The underlying methods create an NxM matrix where N is the total number of sub-runs:
https://github.com/neutrons/PyRS/blob/fa6600fdcc5c68a2d499f1b566ac119497ad33fc/pyrs/core/workspaces.py#L778

This sub-run list is not propagate into the methods that saves the reduced data to the project file. 
https://github.com/neutrons/PyRS/blob/fa6600fdcc5c68a2d499f1b566ac119497ad33fc/pyrs/core/powder_pattern.py#L173

As a result, the sub-run indexes that were not included in the input list have garbage values.
![Screenshot from 2020-07-29 13-09-21](https://user-images.githubusercontent.com/32335915/88844513-c5ba6d80-d1b0-11ea-8b63-b13194673260.png)

**Comment by jmborr** [comment]
@fanchercm I am tryting to understand more about the reduction process but looking at the picture I got confused. In this example I was under the impression that the user had not included the last subrun (index=9) and that's why the corresponding row it's full of zeros. However, the plot shows angles for the first subrun (which has some Nan) values. So, which one do you want to draw attention to with the plot?

**Comment by fanchercm** [comment]
@jmborr The first and last runs were excluded. I supplied the following list for the sub-run to reduce 1086
`sub-runs = [2, 3, 4, 5, 6, 7, 8]`

The problem is that the save functions do not get exposed to the exclude list

**Comment by jmborr** [comment]
@fanchercm I see two different saving modes:
1. under node `reduced_diffraction_data`, a `subruns` list could be saved listing only the included subruns, and then the `2theta` array would contain only seven rows.
2. don't save a `subruns` list and the `2theta` array would contain ten rows, three of them filled with `nan` values.

**Comment by jmborr** [comment]
from Chris:  

The save experimental data method already has the code to accept a sub-run list  
https://github.com/neutrons/PyRS/blob/fa6600fdcc5c68a2d499f1b566ac119497ad33fc/pyrs/core/workspaces.py#L826  
The method to save diffraction data does not have the method already built   https://github.com/neutrons/PyRS/blob/fa6600fdcc5c68a2d499f1b566ac119497ad33fc/pyrs/core/workspaces.py#L898

**Comment by peterfpeterson** [comment]
merged PR closed this
