### ISSUE TITLE
HB2B project file

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#65]
Design and implement HB2B project file. It includes

- [ ] Design document

- [ ] Implementation in PyRS

- [ ] Conversion of test files

This is a high level issue containing a series of other issues, including
- [ ] #93: instrument geometry (wave length), calibration (mask) and efficiency (vanadium)
- [ ] #88: calibrated geometry
- [ ] #86 
- [ ] #87 

**Proposed project file structure**

- raw data
   - run a
   - run b
   - ... ...
- instrument
  - geometry
  - calibration
- reduced data
  - run a
  - run b
  - ... ...
- peak fitting
  - HKL_1
     - run a
     - run b
  - HKL_2

**Comment by peterfpeterson** [comment]
This is already done
