### ISSUE TITLE
Alternative implementation of stress/strain centered on SampledPoint objects

### ISSUE THREAD

**Issue by jmborr** [neutrons/PyRS#652]
- the design uses `SamplePoint`s as databases containing `Measurement`s from different `PeakCollection`s, peak tags, and directions.
- `SamplePoint`s are queried with specific peak tags, runs, and/or directions to retrieve relevant data from a specific `Measurement`
- Strain/stress calculations are _local_ to each point, thus there's no need to keep references to where the stress values came from which collection
- Measurements of different runs with same motor positions end up on the same `SamplePoint`, thus no need to cluster whole strain objects together.
- Data from all `SamplePoint`s is gathered by the `MultiScan` object and served as a two-column (`xyz`, `datum`) for CSV export, or as a `ScalarFieldSample` for visualization

![design](https://user-images.githubusercontent.com/1136006/89771877-0f6b5800-dacf-11ea-9f49-3ac0252fbb1c.jpg)

**Comment by peterfpeterson** [comment]
This was already done
