### ISSUE TITLE
Default precision for values in CSV ouput

### ISSUE THREAD

**Issue by jefrbunn** [neutrons/PyRS#669]
On issue #615.

Pretty terrible formatting here but Hopefully it will make sense.

Spatial Coordinates (vx, vyx, vz, sx, sz, sz): Units (mm)= Precision {:. 2f}
d-spacing: Units (angstrom) = Precision {:. 7f}
FWHM: Precision {:. 2f}
Strain: Units (microstrain) displayed as strain (10E-6) : {:. 0f}
Stress: Units (MPa) ; {:. 0f}

errors should be displayed in the same precision as the values.

**Comment by williamfgc** [comment]
@jefrbunn I"m going through this. I have a quick question, does this line `Stress: Units (MPa) ; {:. 0f}` mean that Stress is always an integer? 

> errors should be displayed in the same precision as the values.
this is a collateral, the errors are integers as well?

**Comment by jefrbunn** [comment]
So the stress values need to be an integer, but in MPa. Currently I believe the units are not being taken into account. So we are reporting them in GPa. So we need to have them divided by 1E-3 to be correct I believe since we are giving our E in GPa it needs to be corrected. 

The same for microstrain. Currently we are reporting strain and not 1E-6 strain (microstrain).

**Comment by peterfpeterson** [comment]
The units will be handled in #727

**Comment by williamfgc** [comment]
Addressed as part of #710
