### ISSUE TITLE
File not saved as .h5

### ISSUE THREAD

**Issue by jefrbunn** [neutrons/PyRS#747]
When clicking File>Save As in the Peak fitting window the file should default to save as an .h5

**Comment by rosswhitfield** [comment]
You should be able to set the filter at https://github.com/neutrons/PyRS/blob/6f51a501b7dd42c1948914b779f65a53e1aad591/pyrs/interface/gui_helper.py#L67 to `"HidraProjectFile (*.h5);;All Files (*)"` and it should do the right thing.
