### ISSUE TITLE
JOSS: it's not clearly described in the manuscript how this software compares to other commonly used packages.

### ISSUE THREAD

**Issue by andyfaff** [neutrons/PyRS#783]
https://github.com/openjournals/joss-reviews/issues/4104

This doesn't apply for the reduction and processing capabilities of the software, as it is bespoke to the instrumentation at ORNL. However, the JOSS manuscript does not describe how PyRS' data analysis capabilities compare to other available packages. The JOSS guidelines suggest the authors should add this.

**Comment by fanchercm** [comment]
A discussion of how the pyRS capabilities compare with the community was added to the paper:
The overall functionality of pyRS is similar to the stress texture calculator package developed at FRM-II, which includes modules for data reduction, analysis, and visualization.[@Randau2011] Nuance differences in how raw data are saved necessitated the development of a new package tailored to the needs of the HIDRA instrument and its unique user community. The peak fitting in pyRS utilizes the mantid framework, a standardized collection of algorithms that are tailored for processing neutron diffraction and scattering data.[@Arnold2014a] Mantid implements peak shape functions common to neutron diffraction data (e.g., Gaussian, Lorentz, pseudo-Voigt, Voigt, etc...). The underlying peak fitting capabilities in Mantid are similar to the LMFIT python package.[@Newville2021] The interpretation of peak fitting results using equations 1-3 follow principle stress/strain analysis used by the neutron engineering diffraction community.[@Huchings] While the underlying mathematics are common to the neutron community, the visualization capabilities of pyRS are unique and were designed to facilitate users to visualize neutron mapping results more readily.
