### ISSUE TITLE
JOSS: Installation: Does installation proceed as outlined in the documentation?

### ISSUE THREAD

**Issue by sangpham171** [neutrons/PyRS#785]
Hello,
I try to run the pyplot, but no success. Is it an obligation to use Linux? because i am using window and python version 3.9.10
I have already installed all the requirements except the mantide-workbench, I can't find with pip.

Here is the problem:

C:\PyRS-next>py scripts/pyrsplot
C:\PyRS-next\scripts\pyrsplot:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "C:\PyRS-next\scripts\pyrsplot", line 6, in <module>
    import pyrs.interface.pyrs_main
ModuleNotFoundError: No module named 'pyrs.interface'

If not, do you have an .exe file to test the program. Because for a normal user it might be difficult to install all the dependencies.
https://github.com/openjournals/joss-reviews/issues/4104

**Comment by fanchercm** [comment]
We have never tested pyRS from windows. My best guess is that there is a path issue related to running pyrsplot. Please see the JOSS_ISSUE branch for an updated readme. At this moment we do not have compiled version of the software. We are waiting for mantid dependency issues to be resolved before deploying pyRS as part of an anaconda release.

**Comment by rkurchin** [comment]
Mentioning [JOSS review issue](https://github.com/openjournals/joss-reviews/issues/4104) to link these together for easier tracking

**Comment by sangpham171** [comment]
I have no experience with Linux. 
If Linux is an obligation, I don't think I'm a good candidate for the reviewer. All my applications are developed in windows environment.
I don't know if you can change the reviewer, but if so, you can choose another one who knows the Linux environment.

**Comment by fanchercm** [comment]
@sangpham171  Please try the following:
From the PyRS directory, start the user interface
`set PYTHONPATH=%PATH%;%PYTHONPATH%; python scripts/pyrsplot`

**Comment by andyfaff** [comment]
The instructions now work for me on the JOSS_ISSUE branch.
