### ISSUE TITLE
JOSS: running the tests.

### ISSUE THREAD

**Issue by andyfaff** [neutrons/PyRS#786]
On the JOSS_ISSUE branch the test suite has 5 failures. These are:
<img width="767" alt="Screen Shot 2022-04-08 at 1 21 28 pm" src="https://user-images.githubusercontent.com/702934/162356636-ad2d437a-d20c-4a0e-aa03-690784ff01b1.png">

Several of them appear with a file dialog to manually select files. I have no idea of which files to select.

(xref https://github.com/openjournals/joss-reviews/issues/4104)

**Comment by fanchercm** [comment]
Some screen resolutions can cause an error to occur. The tests have been updated in JOSS_ISSUE to address the test failures.
