### ISSUE TITLE
JOSS: community contribution guidelines

### ISSUE THREAD

**Issue by andyfaff** [neutrons/PyRS#787]
The JOSS reviewer guidelines ask:

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I can't see this anywhere in the docs/README.rst, etc.

**Comment by fanchercm** [comment]
The community contributions were added to the README.rst in the pyRS home directory for the JOSS_ISSUE. The primary branch has not been updated yet. 

'Contributing to pyRS
--------------------
If you want to suggest changes of a feature or the inclusion of new features, you can either 1) [fork](https://github.com/neutrons/PyRS/fork) the repository to work on it and create an [issue](https://github.com/neutrons/PyRS/issues/new) to discuss it before proceeding with a pull request, or 2) create an [issue](https://github.com/neutrons/PyRS/issues/new) with your suggestion for others to discuss and potentially work on it.
'
