### ISSUE TITLE
JOSS: can't find the example files

### ISSUE THREAD

**Issue by andyfaff** [neutrons/PyRS#788]
I'm trying to run the examples at https://neutrons-pyrs.readthedocs.io/en/latest/example/example.html#pyrs-example-use, but can't find the examples referred to [here](https://neutrons-pyrs.readthedocs.io/en/latest/example/example.html#load-measured-data). In which directory are they?

(xref https://github.com/openjournals/joss-reviews/issues/4104)

**Comment by fanchercm** [comment]
From the JOSS_ISSUE branch the files are under the "example" folder. I have updated the readthedocs to help clarify the location of the data. 

'example/HB2B_2246.h5'
'example/HB2B_2247.h5'
'example/HB2B_2251.h5'

**Comment by andyfaff** [comment]
Great, didn't see that
