### ISSUE TITLE
Installing PyRS - Problem with mamba

### ISSUE THREAD

**Issue by aapaecklar** [neutrons/PyRS#845]
Hello, 

I am trying to install PyRs with:

**mamba env create --name pyrs --file environment.yml**

but unfortunatley, I get the following error message:

**EnvironmentFileNotFound: '/home/paecklar/environment.yml' file not found**

Thank you in advance for your help!

With kind regards,
Arnold

**Comment by brettceiffert** [comment]
Arnold,

Have you cloned the repository yet? Here are the steps to run the command you are trying to run successfully:

1. Clone the repository to your machine
2. `cd` into the PyRS folder produced from cloning the repository
3. Execute the command you're trying to run

The environment.yml is at the top level of PyRS folder.

Let me know how that goes.

Brett

**Comment by aapaecklar** [comment]
Hello Brett,

thank you for your feedback. Yes, that was my problem and I was able to install it. I was very naively following the instruction. Not having been familiar at that time with mamba (or what mamba is), I for whatever reason assumed that it would also download the package automatically. 

Nevertheless, what was initially also not quite clear to me which dependencies list to use, especially since the installation instructions are a little bit different on github vs. the readthedocs.io page.

With kind regards,
Arnold
