### ISSUE TITLE
Hidra project file: Read and write fitted peak parameters

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#87]
Fitted peak's parameters value and error will be written to Hidra project file.

The peak parameters' value will be read from the project file for further data analysis.

**Comment by fanchercm** [comment]
testing data for fitting
/tests/data/16-1_LD.cor_Log.hdf5

**Comment by wdzhou** [comment]
```/tests/data/16-1_LD.cor_Log.hdf5``` may not be in a good hidra project format.  I need to modify it.   Anyway, I am going to take this issue.
