### ISSUE TITLE
PyRS: wave length, mask and vanadium

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#93]
This is one of last part for instrument related parameters of Hidra project file.

Reference: meeting note (inside meeting invitation) on 9/18/2019

*	Wave length:
        ```
        /instrument/monochromator setting/ ... .../ 
        ```
      - same wave length to all sub runs
      - only calibrated wave length in project file
      - raw wave length comes from a table with setting

*	Mask
        ```
        main entry/mask/detector/
        ```
        ```
        main entry/mask/solid angle/ 
        ```
      - data will be a range of solid angles and number of patterns to generate. example solid angle range = -8, 8, number of pattern = 3

*	Vanadium (efficiency correction)
        ```
        ... /main entry/calibration/efficency: numpy array with 1024**2...
        ```
       - add the run  number created from to the attribute

**Comment by peterfpeterson** [comment]
#347 is taking the remaining part of this issue over
