### ISSUE TITLE
Export reduction summary

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#97]
**CSV file format**

- Header: fixed information
```
# IPTS number
# Run
# Scan title
# Sample name
# Item number
# HKL phase
# Strain direction
# Monochromator setting (such as Si111... for wave length)
# Calibration file, Hidra project file
# Manual vs auto reduction
```
- Header: Optionally meta data for constant variables
   - Example:
  ``` 
  # motor sx = 1.3 +/- 0.001 
  ```
   - If any of these change it within 5-sigma, treat it as constant and put it to header under constant motors/variables

- Body
  ```
  sub-run, vx, vy, vz, sx, sy, sz, phi, chi, omega, 2theta, S1 width, S1 height, S1 Distance, Radial distance, effective peak parameters
  ```
  - Peak name: Label_1_Intensity, Label_1_FWHM...

**Comment by quantumsteve** [comment]
https://github.com/neutrons/PyRS/blob/master/pyrs/core/workspaces.py

**Comment by wdzhou** [comment]
@quantumsteve Please remind me to talk with you about this.

**Comment by quantumsteve** [comment]
https://github.com/neutrons/PyRS/blob/409feb0f66d5f7490491b49b2aa77bd43695da06/pyrs/core/pyrscore.py#L253

**Comment by quantumsteve** [comment]
https://github.com/neutrons/PyRS/blob/master/tests/integration/test_fit_peaks.py

**Comment by JeanBilheux** [comment]
in the Fitting UI, right ?
